name: 🚀 Release & Publish
on:
  push:
    branches:
      - test
jobs:
  cd:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          scope: "@ngaox"
          cache: "yarn"
      - uses: chaospad/releaser@v1
        id: releaser
      - run: echo "Its == true"
        if: steps.releaser.outputs.released
      - run: echo "Its == 'true'"
        if: steps.releaser.outputs.released == 'true'
